version: '3'
services:
#    kimos-service:
#      build: .
#      ports:
#        - "10101:10101"
#      depends_on:
#        - postgres
#        - redis
#      environment:
#        - DB_HOST=postgres
#        - DB_NAME=kimos
#        - DB_USER=kimos
#        - DB_PASS=1234
#        - DB_PORT=20202
#        - REDIS_HOST=redis
#        - REDIS_PORT=6379
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kimos
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kimos
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    ports:
      - "6379:6379"
    image: redis:latest
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data: